### ISSUE TITLE
Away mode. Doesn't work

### ISSUE THREAD

**Issue by pasqualeflorio93-ctrl** [codykociemba/NoLongerEvil-Thermostat#51]
Away mode doesn't work. The button turns orange but the thermostat doesn't activate the function. Is this a problem with me? Thanks

**Comment by arishokri** [comment]
I have the same issue. Using OG Nest App, away mode used to trigger "ECO Mode" but currently the away mode doesn't set my Eco temperature. As you mentioned the interface shows activated Away Mode, which I can still deactivate but this doesn't change the temperature settings.

**Comment by arkpope** [comment]
It's odd, mine keeps getting auto activated, at least on the dashboard. And the heat is not on unless I tap the actual Nest.

**Comment by ddsdude** [comment]
When I try to turn off Away Mode, it just turns back on in the UI.

**Comment by codykociemba** [comment]
This should be fixed in the latest update, give it a try and let me know. Thanks!

**Comment by ddsdude** [comment]
It is indeed fixed! Thank you!

**Comment by arishokri** [comment]
Dumb questions, was the firmware part of this update as well? Meaning should I flash the firmware again?

**Comment by coolguymatt** [comment]
I still have this issue. Away mode doesn’t trigger eco mode settings. I only flashed the thermostat a few days ago. Is there something I can try to get it to work?

**Comment by 26tajeen** [comment]
@arkpope are you saying  your device is auto activating eco mode? If so - mine is too!

**Comment by gartkb** [comment]
I can't seem to turn off away from remote
